import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author daniel
 */
public class Form1 extends javax.swing.JFrame {
String nama_file = "D:/Mahasiswa.txt";
BufferedWriter buffered_Writer;

public void add()
{
    Add.setText("ADD"); 
}

public void update()
{ 
Add.setText("UPDATE");
Tabel tabel_ = new Tabel();
Text1.setText(tabel_.nama);
Text2.setText(tabel_.nim);
Text3.setText(tabel_.asal);
Text4.setText(tabel_.nomor);
}

public String Nama_,Nim_,Asal_,Nomor_,isi;
    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nama = new javax.swing.JLabel();
        Text1 = new javax.swing.JTextField();
        Asal = new javax.swing.JLabel();
        Text2 = new javax.swing.JTextField();
        NIM = new javax.swing.JLabel();
        Text3 = new javax.swing.JTextField();
        Telpon = new javax.swing.JLabel();
        Text4 = new javax.swing.JTextField();
        Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nama.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        Nama.setText("Nama : ");

        Text1.setBackground(new java.awt.Color(153, 255, 204));
        Text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text1ActionPerformed(evt);
            }
        });

        Asal.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        Asal.setText("Asal : ");

        Text2.setBackground(new java.awt.Color(153, 255, 204));

        NIM.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        NIM.setText("NIM : ");

        Text3.setBackground(new java.awt.Color(153, 255, 204));

        Telpon.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        Telpon.setText("No.Telp : ");

        Text4.setBackground(new java.awt.Color(153, 255, 204));

        Add.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        Add.setText("ADD");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Telpon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(Text4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nama)
                            .addComponent(NIM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Asal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Text3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIM))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Asal)
                    .addComponent(Text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telpon)
                    .addComponent(Text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(Add)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        if(Add.getText()=="ADD"){
        Tabel tabel = new Tabel();
        Nama_ = Text1.getText();
        Nim_ = Text2.getText();
        Asal_ = Text3.getText();
        Nomor_ = Text4.getText();
        isi= Nama_+"#"+Nim_+"#"+Asal_+"#"+Nomor_+"#";
        try {
		FileWriter fileWriter = new FileWriter(nama_file,true);
		BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
		bufferedWriter.write(isi);
                bufferedWriter.newLine();
                bufferedWriter.flush();
	        bufferedWriter.close(); 
	        }
	        catch(FileNotFoundException ex) {
	            System.out.println("Unable to open file '" + nama_file + "'");                
	        }
	        catch(IOException ex) {
	        System.out.println(
	        "Error reading file '" + nama_file + "'");                  
	        }
        dispose();
        tabel.setVisible(true);
        }
       else if(Add.getText()=="UPDATE")
       {
       if(Text1.getText()==null) {
       Tabel tabel = new Tabel();
       dispose();
       tabel.setVisible(true);
       }else 
       {
        Tabel tabel = new Tabel();
        Nama_ = Text1.getText();
        Nim_ =  Text2.getText();
        Asal_ = Text3.getText();
        Nomor_ = Text4.getText();
        isi = Nama_+"#"+Nim_+"#"+Asal_+"#"+Nomor_+"#";
        try {    
        FileWriter fileWriter = new FileWriter(nama_file,true);
        BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
	bufferedWriter.write(isi);
        bufferedWriter.flush();
        bufferedWriter.newLine();
        }catch (IOException ex) 
        {
        }finally{                     
	if (buffered_Writer != null) 
        try 
        {
	    buffered_Writer.close();
	}catch (IOException e2) {   
	}
        dispose();
        tabel.setVisible(true);
        }
        }
       }
    }//GEN-LAST:event_AddActionPerformed

    private void Text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel Asal;
    private javax.swing.JLabel NIM;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Telpon;
    private javax.swing.JTextField Text1;
    private javax.swing.JTextField Text2;
    private javax.swing.JTextField Text3;
    private javax.swing.JTextField Text4;
    // End of variables declaration//GEN-END:variables
}
